global:
  scrape_interval:     1s
  evaluation_interval: 10s

rule_files:
  - "rules/*rules.yaml"

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: node
    basic_auth:
      username: {http_basic_auth_user}
      password: {http_basic_auth_password}
    metrics_path: /metrics/node/host
    scheme: http
    static_configs:
      - targets:
          - {target}
  - job_name: ob_basic
    basic_auth:
      username: {http_basic_auth_user}
      password: {http_basic_auth_password}
    metrics_path: /metrics/ob/basic
    scheme: http
    static_configs:
      - targets:
          - {target}
  - job_name: ob_extra
    basic_auth:
      username: {http_basic_auth_user}
      password: {http_basic_auth_password}
    metrics_path: /metrics/ob/extra
    scheme: http
    static_configs:
      - targets:
          - {target}
  - job_name: agent
    basic_auth:
      username: {http_basic_auth_user}
      password: {http_basic_auth_password}
    metrics_path: /metrics/stat
    scheme: http
    static_configs:
      - targets:
          - {target}
